apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argouser-serviceaccount.yaml
  - readwrite-role.yaml
  - readwrite-rolebinding.yaml
  - workflow-role.yaml
  - workflow-rolebinding.yaml
  - workflow-serviceaccount.yaml
  - workflow-secret.yaml
