apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.12.2/cert-manager.yaml
  - resources/letsencrypt-prod-clusterissuer.yaml
  - resources/letsencrypt-staging-clusterissuer.yaml

patchesStrategicMerge:
  - overlays/cert-manager-sa.yaml
